//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("FORMATIONModel", "FK_FILIEIRE_Tribunal", "Tribunal", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(projet_formation.Tribunal), "Filiere", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(projet_formation.Filiere), true)]
[assembly: EdmRelationshipAttribute("FORMATIONModel", "FK_fonctionnaire_Filiere", "Filiere", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(projet_formation.Filiere), "fonctionnaire", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(projet_formation.fonctionnaire), true)]
[assembly: EdmRelationshipAttribute("FORMATIONModel", "FK_Formation__formateurs", "formateurs", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(projet_formation.formateurs), "Formation", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(projet_formation.Formation), true)]
[assembly: EdmRelationshipAttribute("FORMATIONModel", "FK_Formation_Tribunal", "Tribunal", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(projet_formation.Tribunal), "Formation", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(projet_formation.Formation), true)]
[assembly: EdmRelationshipAttribute("FORMATIONModel", "formation_fonctionnaire", "fonctionnaire", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(projet_formation.fonctionnaire), "Formation", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(projet_formation.Formation))]

#endregion

namespace projet_formation
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class FORMATIONEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new FORMATIONEntities object using the connection string found in the 'FORMATIONEntities' section of the application configuration file.
        /// </summary>
        public FORMATIONEntities() : base("name=FORMATIONEntities", "FORMATIONEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new FORMATIONEntities object.
        /// </summary>
        public FORMATIONEntities(string connectionString) : base(connectionString, "FORMATIONEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new FORMATIONEntities object.
        /// </summary>
        public FORMATIONEntities(EntityConnection connection) : base(connection, "FORMATIONEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<administrateur> administrateur
        {
            get
            {
                if ((_administrateur == null))
                {
                    _administrateur = base.CreateObjectSet<administrateur>("administrateur");
                }
                return _administrateur;
            }
        }
        private ObjectSet<administrateur> _administrateur;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Filiere> Filiere
        {
            get
            {
                if ((_Filiere == null))
                {
                    _Filiere = base.CreateObjectSet<Filiere>("Filiere");
                }
                return _Filiere;
            }
        }
        private ObjectSet<Filiere> _Filiere;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<fonctionnaire> fonctionnaire
        {
            get
            {
                if ((_fonctionnaire == null))
                {
                    _fonctionnaire = base.CreateObjectSet<fonctionnaire>("fonctionnaire");
                }
                return _fonctionnaire;
            }
        }
        private ObjectSet<fonctionnaire> _fonctionnaire;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<formateurs> formateurs
        {
            get
            {
                if ((_formateurs == null))
                {
                    _formateurs = base.CreateObjectSet<formateurs>("formateurs");
                }
                return _formateurs;
            }
        }
        private ObjectSet<formateurs> _formateurs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Formation> Formation
        {
            get
            {
                if ((_Formation == null))
                {
                    _Formation = base.CreateObjectSet<Formation>("Formation");
                }
                return _Formation;
            }
        }
        private ObjectSet<Formation> _Formation;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Tribunal> Tribunal
        {
            get
            {
                if ((_Tribunal == null))
                {
                    _Tribunal = base.CreateObjectSet<Tribunal>("Tribunal");
                }
                return _Tribunal;
            }
        }
        private ObjectSet<Tribunal> _Tribunal;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the administrateur EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToadministrateur(administrateur administrateur)
        {
            base.AddObject("administrateur", administrateur);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Filiere EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFiliere(Filiere filiere)
        {
            base.AddObject("Filiere", filiere);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the fonctionnaire EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTofonctionnaire(fonctionnaire fonctionnaire)
        {
            base.AddObject("fonctionnaire", fonctionnaire);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the formateurs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToformateurs(formateurs formateurs)
        {
            base.AddObject("formateurs", formateurs);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Formation EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFormation(Formation formation)
        {
            base.AddObject("Formation", formation);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Tribunal EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTribunal(Tribunal tribunal)
        {
            base.AddObject("Tribunal", tribunal);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FORMATIONModel", Name="administrateur")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class administrateur : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new administrateur object.
        /// </summary>
        /// <param name="login">Initial value of the login property.</param>
        /// <param name="mot_d_passe">Initial value of the mot_d_passe property.</param>
        public static administrateur Createadministrateur(global::System.String login, global::System.String mot_d_passe)
        {
            administrateur administrateur = new administrateur();
            administrateur.login = login;
            administrateur.mot_d_passe = mot_d_passe;
            return administrateur;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String login
        {
            get
            {
                return _login;
            }
            set
            {
                if (_login != value)
                {
                    OnloginChanging(value);
                    ReportPropertyChanging("login");
                    _login = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("login");
                    OnloginChanged();
                }
            }
        }
        private global::System.String _login;
        partial void OnloginChanging(global::System.String value);
        partial void OnloginChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String mot_d_passe
        {
            get
            {
                return _mot_d_passe;
            }
            set
            {
                if (_mot_d_passe != value)
                {
                    Onmot_d_passeChanging(value);
                    ReportPropertyChanging("mot_d_passe");
                    _mot_d_passe = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("mot_d_passe");
                    Onmot_d_passeChanged();
                }
            }
        }
        private global::System.String _mot_d_passe;
        partial void Onmot_d_passeChanging(global::System.String value);
        partial void Onmot_d_passeChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FORMATIONModel", Name="Filiere")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Filiere : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Filiere object.
        /// </summary>
        /// <param name="iD_Filere">Initial value of the ID_Filere property.</param>
        /// <param name="nom">Initial value of the nom property.</param>
        /// <param name="iD_tribunal">Initial value of the ID_tribunal property.</param>
        public static Filiere CreateFiliere(global::System.String iD_Filere, global::System.String nom, global::System.String iD_tribunal)
        {
            Filiere filiere = new Filiere();
            filiere.ID_Filere = iD_Filere;
            filiere.nom = nom;
            filiere.ID_tribunal = iD_tribunal;
            return filiere;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID_Filere
        {
            get
            {
                return _ID_Filere;
            }
            set
            {
                if (_ID_Filere != value)
                {
                    OnID_FilereChanging(value);
                    ReportPropertyChanging("ID_Filere");
                    _ID_Filere = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ID_Filere");
                    OnID_FilereChanged();
                }
            }
        }
        private global::System.String _ID_Filere;
        partial void OnID_FilereChanging(global::System.String value);
        partial void OnID_FilereChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nom
        {
            get
            {
                return _nom;
            }
            set
            {
                OnnomChanging(value);
                ReportPropertyChanging("nom");
                _nom = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nom");
                OnnomChanged();
            }
        }
        private global::System.String _nom;
        partial void OnnomChanging(global::System.String value);
        partial void OnnomChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID_tribunal
        {
            get
            {
                return _ID_tribunal;
            }
            set
            {
                OnID_tribunalChanging(value);
                ReportPropertyChanging("ID_tribunal");
                _ID_tribunal = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ID_tribunal");
                OnID_tribunalChanged();
            }
        }
        private global::System.String _ID_tribunal;
        partial void OnID_tribunalChanging(global::System.String value);
        partial void OnID_tribunalChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FORMATIONModel", "FK_FILIEIRE_Tribunal", "Tribunal")]
        public Tribunal Tribunal
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tribunal>("FORMATIONModel.FK_FILIEIRE_Tribunal", "Tribunal").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tribunal>("FORMATIONModel.FK_FILIEIRE_Tribunal", "Tribunal").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Tribunal> TribunalReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tribunal>("FORMATIONModel.FK_FILIEIRE_Tribunal", "Tribunal");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Tribunal>("FORMATIONModel.FK_FILIEIRE_Tribunal", "Tribunal", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FORMATIONModel", "FK_fonctionnaire_Filiere", "fonctionnaire")]
        public EntityCollection<fonctionnaire> fonctionnaire
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<fonctionnaire>("FORMATIONModel.FK_fonctionnaire_Filiere", "fonctionnaire");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<fonctionnaire>("FORMATIONModel.FK_fonctionnaire_Filiere", "fonctionnaire", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FORMATIONModel", Name="fonctionnaire")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class fonctionnaire : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new fonctionnaire object.
        /// </summary>
        /// <param name="sOM">Initial value of the SOM property.</param>
        /// <param name="nom_f">Initial value of the nom_f property.</param>
        /// <param name="prenom_f">Initial value of the prenom_f property.</param>
        /// <param name="poste">Initial value of the poste property.</param>
        /// <param name="date_embauche">Initial value of the date_embauche property.</param>
        /// <param name="iD_Filiere">Initial value of the ID_Filiere property.</param>
        public static fonctionnaire Createfonctionnaire(global::System.String sOM, global::System.String nom_f, global::System.String prenom_f, global::System.String poste, global::System.DateTime date_embauche, global::System.String iD_Filiere)
        {
            fonctionnaire fonctionnaire = new fonctionnaire();
            fonctionnaire.SOM = sOM;
            fonctionnaire.nom_f = nom_f;
            fonctionnaire.prenom_f = prenom_f;
            fonctionnaire.poste = poste;
            fonctionnaire.date_embauche = date_embauche;
            fonctionnaire.ID_Filiere = iD_Filiere;
            return fonctionnaire;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SOM
        {
            get
            {
                return _SOM;
            }
            set
            {
                if (_SOM != value)
                {
                    OnSOMChanging(value);
                    ReportPropertyChanging("SOM");
                    _SOM = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("SOM");
                    OnSOMChanged();
                }
            }
        }
        private global::System.String _SOM;
        partial void OnSOMChanging(global::System.String value);
        partial void OnSOMChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nom_f
        {
            get
            {
                return _nom_f;
            }
            set
            {
                Onnom_fChanging(value);
                ReportPropertyChanging("nom_f");
                _nom_f = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nom_f");
                Onnom_fChanged();
            }
        }
        private global::System.String _nom_f;
        partial void Onnom_fChanging(global::System.String value);
        partial void Onnom_fChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String prenom_f
        {
            get
            {
                return _prenom_f;
            }
            set
            {
                Onprenom_fChanging(value);
                ReportPropertyChanging("prenom_f");
                _prenom_f = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("prenom_f");
                Onprenom_fChanged();
            }
        }
        private global::System.String _prenom_f;
        partial void Onprenom_fChanging(global::System.String value);
        partial void Onprenom_fChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String adresse
        {
            get
            {
                return _adresse;
            }
            set
            {
                OnadresseChanging(value);
                ReportPropertyChanging("adresse");
                _adresse = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("adresse");
                OnadresseChanged();
            }
        }
        private global::System.String _adresse;
        partial void OnadresseChanging(global::System.String value);
        partial void OnadresseChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String poste
        {
            get
            {
                return _poste;
            }
            set
            {
                OnposteChanging(value);
                ReportPropertyChanging("poste");
                _poste = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("poste");
                OnposteChanged();
            }
        }
        private global::System.String _poste;
        partial void OnposteChanging(global::System.String value);
        partial void OnposteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime date_embauche
        {
            get
            {
                return _date_embauche;
            }
            set
            {
                Ondate_embaucheChanging(value);
                ReportPropertyChanging("date_embauche");
                _date_embauche = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("date_embauche");
                Ondate_embaucheChanged();
            }
        }
        private global::System.DateTime _date_embauche;
        partial void Ondate_embaucheChanging(global::System.DateTime value);
        partial void Ondate_embaucheChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String lieu_naissance
        {
            get
            {
                return _lieu_naissance;
            }
            set
            {
                Onlieu_naissanceChanging(value);
                ReportPropertyChanging("lieu_naissance");
                _lieu_naissance = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("lieu_naissance");
                Onlieu_naissanceChanged();
            }
        }
        private global::System.String _lieu_naissance;
        partial void Onlieu_naissanceChanging(global::System.String value);
        partial void Onlieu_naissanceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> date_naissance
        {
            get
            {
                return _date_naissance;
            }
            set
            {
                Ondate_naissanceChanging(value);
                ReportPropertyChanging("date_naissance");
                _date_naissance = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("date_naissance");
                Ondate_naissanceChanged();
            }
        }
        private Nullable<global::System.DateTime> _date_naissance;
        partial void Ondate_naissanceChanging(Nullable<global::System.DateTime> value);
        partial void Ondate_naissanceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID_Filiere
        {
            get
            {
                return _ID_Filiere;
            }
            set
            {
                OnID_FiliereChanging(value);
                ReportPropertyChanging("ID_Filiere");
                _ID_Filiere = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ID_Filiere");
                OnID_FiliereChanged();
            }
        }
        private global::System.String _ID_Filiere;
        partial void OnID_FiliereChanging(global::System.String value);
        partial void OnID_FiliereChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FORMATIONModel", "FK_fonctionnaire_Filiere", "Filiere")]
        public Filiere Filiere
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Filiere>("FORMATIONModel.FK_fonctionnaire_Filiere", "Filiere").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Filiere>("FORMATIONModel.FK_fonctionnaire_Filiere", "Filiere").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Filiere> FiliereReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Filiere>("FORMATIONModel.FK_fonctionnaire_Filiere", "Filiere");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Filiere>("FORMATIONModel.FK_fonctionnaire_Filiere", "Filiere", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FORMATIONModel", "formation_fonctionnaire", "Formation")]
        public EntityCollection<Formation> Formation
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Formation>("FORMATIONModel.formation_fonctionnaire", "Formation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Formation>("FORMATIONModel.formation_fonctionnaire", "Formation", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FORMATIONModel", Name="formateurs")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class formateurs : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new formateurs object.
        /// </summary>
        /// <param name="matricule_form">Initial value of the matricule_form property.</param>
        public static formateurs Createformateurs(global::System.String matricule_form)
        {
            formateurs formateurs = new formateurs();
            formateurs.matricule_form = matricule_form;
            return formateurs;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String matricule_form
        {
            get
            {
                return _matricule_form;
            }
            set
            {
                if (_matricule_form != value)
                {
                    Onmatricule_formChanging(value);
                    ReportPropertyChanging("matricule_form");
                    _matricule_form = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("matricule_form");
                    Onmatricule_formChanged();
                }
            }
        }
        private global::System.String _matricule_form;
        partial void Onmatricule_formChanging(global::System.String value);
        partial void Onmatricule_formChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NOM
        {
            get
            {
                return _NOM;
            }
            set
            {
                OnNOMChanging(value);
                ReportPropertyChanging("NOM");
                _NOM = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NOM");
                OnNOMChanged();
            }
        }
        private global::System.String _NOM;
        partial void OnNOMChanging(global::System.String value);
        partial void OnNOMChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String prenom
        {
            get
            {
                return _prenom;
            }
            set
            {
                OnprenomChanging(value);
                ReportPropertyChanging("prenom");
                _prenom = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("prenom");
                OnprenomChanged();
            }
        }
        private global::System.String _prenom;
        partial void OnprenomChanging(global::System.String value);
        partial void OnprenomChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String grade
        {
            get
            {
                return _grade;
            }
            set
            {
                OngradeChanging(value);
                ReportPropertyChanging("grade");
                _grade = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("grade");
                OngradeChanged();
            }
        }
        private global::System.String _grade;
        partial void OngradeChanging(global::System.String value);
        partial void OngradeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FORMATIONModel", "FK_Formation__formateurs", "Formation")]
        public EntityCollection<Formation> Formation
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Formation>("FORMATIONModel.FK_Formation__formateurs", "Formation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Formation>("FORMATIONModel.FK_Formation__formateurs", "Formation", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FORMATIONModel", Name="Formation")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Formation : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Formation object.
        /// </summary>
        /// <param name="id_formation">Initial value of the id_formation property.</param>
        /// <param name="matricule_form">Initial value of the matricule_form property.</param>
        /// <param name="date_debut">Initial value of the date_debut property.</param>
        /// <param name="date_fin">Initial value of the date_fin property.</param>
        /// <param name="nom_for">Initial value of the nom_for property.</param>
        /// <param name="id_tribunal">Initial value of the id_tribunal property.</param>
        public static Formation CreateFormation(global::System.String id_formation, global::System.String matricule_form, global::System.DateTime date_debut, global::System.DateTime date_fin, global::System.String nom_for, global::System.String id_tribunal)
        {
            Formation formation = new Formation();
            formation.id_formation = id_formation;
            formation.matricule_form = matricule_form;
            formation.date_debut = date_debut;
            formation.date_fin = date_fin;
            formation.nom_for = nom_for;
            formation.id_tribunal = id_tribunal;
            return formation;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String id_formation
        {
            get
            {
                return _id_formation;
            }
            set
            {
                if (_id_formation != value)
                {
                    Onid_formationChanging(value);
                    ReportPropertyChanging("id_formation");
                    _id_formation = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("id_formation");
                    Onid_formationChanged();
                }
            }
        }
        private global::System.String _id_formation;
        partial void Onid_formationChanging(global::System.String value);
        partial void Onid_formationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String matricule_form
        {
            get
            {
                return _matricule_form;
            }
            set
            {
                Onmatricule_formChanging(value);
                ReportPropertyChanging("matricule_form");
                _matricule_form = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("matricule_form");
                Onmatricule_formChanged();
            }
        }
        private global::System.String _matricule_form;
        partial void Onmatricule_formChanging(global::System.String value);
        partial void Onmatricule_formChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime date_debut
        {
            get
            {
                return _date_debut;
            }
            set
            {
                Ondate_debutChanging(value);
                ReportPropertyChanging("date_debut");
                _date_debut = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("date_debut");
                Ondate_debutChanged();
            }
        }
        private global::System.DateTime _date_debut;
        partial void Ondate_debutChanging(global::System.DateTime value);
        partial void Ondate_debutChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime date_fin
        {
            get
            {
                return _date_fin;
            }
            set
            {
                Ondate_finChanging(value);
                ReportPropertyChanging("date_fin");
                _date_fin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("date_fin");
                Ondate_finChanged();
            }
        }
        private global::System.DateTime _date_fin;
        partial void Ondate_finChanging(global::System.DateTime value);
        partial void Ondate_finChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nom_for
        {
            get
            {
                return _nom_for;
            }
            set
            {
                Onnom_forChanging(value);
                ReportPropertyChanging("nom_for");
                _nom_for = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nom_for");
                Onnom_forChanged();
            }
        }
        private global::System.String _nom_for;
        partial void Onnom_forChanging(global::System.String value);
        partial void Onnom_forChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String id_tribunal
        {
            get
            {
                return _id_tribunal;
            }
            set
            {
                Onid_tribunalChanging(value);
                ReportPropertyChanging("id_tribunal");
                _id_tribunal = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("id_tribunal");
                Onid_tribunalChanged();
            }
        }
        private global::System.String _id_tribunal;
        partial void Onid_tribunalChanging(global::System.String value);
        partial void Onid_tribunalChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FORMATIONModel", "FK_Formation__formateurs", "formateurs")]
        public formateurs formateurs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<formateurs>("FORMATIONModel.FK_Formation__formateurs", "formateurs").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<formateurs>("FORMATIONModel.FK_Formation__formateurs", "formateurs").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<formateurs> formateursReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<formateurs>("FORMATIONModel.FK_Formation__formateurs", "formateurs");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<formateurs>("FORMATIONModel.FK_Formation__formateurs", "formateurs", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FORMATIONModel", "FK_Formation_Tribunal", "Tribunal")]
        public Tribunal Tribunal
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tribunal>("FORMATIONModel.FK_Formation_Tribunal", "Tribunal").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tribunal>("FORMATIONModel.FK_Formation_Tribunal", "Tribunal").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Tribunal> TribunalReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tribunal>("FORMATIONModel.FK_Formation_Tribunal", "Tribunal");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Tribunal>("FORMATIONModel.FK_Formation_Tribunal", "Tribunal", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FORMATIONModel", "formation_fonctionnaire", "fonctionnaire")]
        public EntityCollection<fonctionnaire> fonctionnaire
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<fonctionnaire>("FORMATIONModel.formation_fonctionnaire", "fonctionnaire");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<fonctionnaire>("FORMATIONModel.formation_fonctionnaire", "fonctionnaire", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FORMATIONModel", Name="Tribunal")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Tribunal : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Tribunal object.
        /// </summary>
        /// <param name="iD_tribunal">Initial value of the ID_tribunal property.</param>
        /// <param name="nom">Initial value of the Nom property.</param>
        /// <param name="adresse">Initial value of the adresse property.</param>
        /// <param name="téléphone">Initial value of the téléphone property.</param>
        public static Tribunal CreateTribunal(global::System.String iD_tribunal, global::System.String nom, global::System.String adresse, global::System.String téléphone)
        {
            Tribunal tribunal = new Tribunal();
            tribunal.ID_tribunal = iD_tribunal;
            tribunal.Nom = nom;
            tribunal.adresse = adresse;
            tribunal.téléphone = téléphone;
            return tribunal;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID_tribunal
        {
            get
            {
                return _ID_tribunal;
            }
            set
            {
                if (_ID_tribunal != value)
                {
                    OnID_tribunalChanging(value);
                    ReportPropertyChanging("ID_tribunal");
                    _ID_tribunal = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ID_tribunal");
                    OnID_tribunalChanged();
                }
            }
        }
        private global::System.String _ID_tribunal;
        partial void OnID_tribunalChanging(global::System.String value);
        partial void OnID_tribunalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nom
        {
            get
            {
                return _Nom;
            }
            set
            {
                OnNomChanging(value);
                ReportPropertyChanging("Nom");
                _Nom = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nom");
                OnNomChanged();
            }
        }
        private global::System.String _Nom;
        partial void OnNomChanging(global::System.String value);
        partial void OnNomChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String adresse
        {
            get
            {
                return _adresse;
            }
            set
            {
                OnadresseChanging(value);
                ReportPropertyChanging("adresse");
                _adresse = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("adresse");
                OnadresseChanged();
            }
        }
        private global::System.String _adresse;
        partial void OnadresseChanging(global::System.String value);
        partial void OnadresseChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String téléphone
        {
            get
            {
                return _téléphone;
            }
            set
            {
                OntéléphoneChanging(value);
                ReportPropertyChanging("téléphone");
                _téléphone = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("téléphone");
                OntéléphoneChanged();
            }
        }
        private global::System.String _téléphone;
        partial void OntéléphoneChanging(global::System.String value);
        partial void OntéléphoneChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FORMATIONModel", "FK_FILIEIRE_Tribunal", "Filiere")]
        public EntityCollection<Filiere> Filiere
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Filiere>("FORMATIONModel.FK_FILIEIRE_Tribunal", "Filiere");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Filiere>("FORMATIONModel.FK_FILIEIRE_Tribunal", "Filiere", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("FORMATIONModel", "FK_Formation_Tribunal", "Formation")]
        public EntityCollection<Formation> Formation
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Formation>("FORMATIONModel.FK_Formation_Tribunal", "Formation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Formation>("FORMATIONModel.FK_Formation_Tribunal", "Formation", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
